name: skill_swap_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^10.1.0
  url_launcher: ^6.1.14


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - images/


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf


    - family: Source Sans 3
      fonts:
        - asset: fonts/SourceSans3-VariableFont_wght.ttf

    - family: Source Sans 3
      fonts:
        - asset: fonts/SourceSans3-Italic-VariableFont_wght.ttf


