// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmxLqQAxA149gFjVKvQJ2uB4yoYV6J85Q',
    appId: '1:517769937007:web:8ffd2dfe2e7ede04e08d9a',
    messagingSenderId: '517769937007',
    projectId: 'fir-series-9728e',
    authDomain: 'fir-series-9728e.firebaseapp.com',
    storageBucket: 'fir-series-9728e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8cS_5t8uhP-24zxqsalj2ltRC4rxJiug',
    appId: '1:517769937007:android:22578644bcb82a88e08d9a',
    messagingSenderId: '517769937007',
    projectId: 'fir-series-9728e',
    storageBucket: 'fir-series-9728e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl5oAZCVHEUnZ0ep2hpSYpZJ--V3T8I1I',
    appId: '1:517769937007:ios:ae4104b55a1a0651e08d9a',
    messagingSenderId: '517769937007',
    projectId: 'fir-series-9728e',
    storageBucket: 'fir-series-9728e.appspot.com',
    iosBundleId: 'com.samin.firebasePrac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl5oAZCVHEUnZ0ep2hpSYpZJ--V3T8I1I',
    appId: '1:517769937007:ios:aa1228196902bbf2e08d9a',
    messagingSenderId: '517769937007',
    projectId: 'fir-series-9728e',
    storageBucket: 'fir-series-9728e.appspot.com',
    iosBundleId: 'com.samin.firebasePrac.RunnerTests',
  );
}
